-- MySQL Script generated by MySQL Workbench
-- Sat Feb 24 13:39:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema canteen_database9
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tbadmin`
-- -----------------------------------------------------
create database canteen_database1;
use canteen_database1;
CREATE TABLE IF NOT EXISTS `tbadmin` (
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbbill` for future
-- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `tbbill` (
 -- `billid` VARCHAR(50) NOT NULL,
-- `orderids` VARCHAR(50) NULL DEFAULT NULL,
--  `customerid` INT NULL DEFAULT NULL,
--  `totalbill` DECIMAL(10,2) NULL DEFAULT NULL,
--  PRIMARY KEY (`billid`),
--  INDEX `customerid` (`customerid` ASC) VISIBLE)
-- ENGINE = InnoDB
-- DEFAULT CHARACTER SET = utf8mb4
-- COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbchef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbchef` (
  `chefid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`chefid`),
  UNIQUE INDEX `username` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbcustomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbcustomer` (
  `customerid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`customerid`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbfeedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbfeedback` (
  `feedbackid` INT NOT NULL AUTO_INCREMENT,
  `customerid` INT NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`feedbackid`),
  INDEX `customerid` (`customerid` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbfoodcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbfoodcategory` (
  `categoryid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`categoryid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbfooditems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbfooditems` (
  `itemid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `rate` VARCHAR(255) NULL DEFAULT NULL,
  `categoryid` INT NULL DEFAULT NULL,
  PRIMARY KEY (`itemid`),
  INDEX `categoryid_idx` (`categoryid` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tborder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tborder` (
  `orderid` INT NOT NULL AUTO_INCREMENT,
  `customerid` INT NULL DEFAULT NULL,
  `itemid` VARCHAR(50) NULL DEFAULT NULL,
  `quantity` VARCHAR(5) NULL DEFAULT NULL,
  `billamount` VARCHAR(50) NULL DEFAULT NULL,
  `paymentstatus` VARCHAR(20) NULL DEFAULT NULL,
  `orderstatus` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`orderid`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbstaff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbstaff` (
  `staffid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`staffid`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
